config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
  :controllers =>{:registrations =>'registrations'},
  :controller => { :invitations => 'devise/invitations' },
  :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

   root 'attendences#index'
   resources :attendences do
     	collection do
  	   	get 'checkin' 
  	   	get 'checkout'
        get 'showattendence'      
     	end
   end

   namespace :admin do
      resources :users do
        member do
          get 'attendence'
          get 'attendences'
          get 'status'
          get 'statuses'
          get 'project'
          get 'projects'
        end
      end
    end

    resources :statuses
    resources :projects

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

	def decrement_invitation_limit!
	 true
	end
	
end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
	belongs_to :user

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
				all.each do |attendence|
				csv << attendence.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/groupproject.rb
class Groupproject < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :groupprojects
  has_many :users, :through => :groupprojects
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
	attr_accessor :hour, :mins,:hour1,:mins1	
end

app/models/user.rb
class User < ActiveRecord::Base
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :attendences
  has_many :statuses
  
  has_many :groupprojects
  has_many :projects, :through => :groupprojects



  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #before_action :authenticate_user!

end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController

	before_action :authenticate_user!

	def checkin
		#@attendence=Attendence.new
		@attendence=Attendence.new(:in_time =>Time.now, :in_date =>Date.today,:user_id =>current_user.id, :ip_in =>request.remote_ip, :workhour => '0')
		if @attendence.save
		  redirect_to attendences_path
		else
			render 'index'
		end
	end

	def checkout
		@attendence = current_user.attendences.last

		if @attendence.in_date == Date.today
	  	@attendence.update(:out_time =>Time.now, :out_date =>Date.today, :ip_out =>request.remote_ip,:status=>'false', :workhour => (Time.now.seconds_since_midnight - @attendence.in_time.seconds_since_midnight).round)
  	else
  		updated_time = Time.new(@attendence.in_date.year, @attendence.in_date.month, @attendence.in_date.day, 23,59,59)
			@attendence.update(:out_time => updated_time, :out_date =>@attendence.in_date, :ip_out =>request.remote_ip,:status=>'true', :workhour => (updated_time.seconds_since_midnight - @attendence.in_time.seconds_since_midnight).round)
		end
		redirect_to attendences_path
	end

	def update
		Attendence.create([:attendence].require(:attendence).permit(:in_date, :in_time, :out_date, :out_time))
	end

 	private
	  def attendence_params
	    params.require(:attendence).permit(:in_date, :in_time, :out_date, :out_time, :ip_in, :ip_out,:user_id)
	  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project= Project.new
	end

	def create
		@project = current_user.projects.create(project_params)				
  	redirect_to project_path(@project)
	end

	def show
	end

	private
	def project_params
		params.require(:project).permit(:proj_name, :client_name, :co_ordinator, :about_project_work, :started_date)
	end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	#include StatusesHelper
	def new
		@status= Status.new
	end

	def create	
		params[:status][:work_hour] = params[:status][:hour1].to_i * 60 * 60 + params[:status][:mins1].to_i * 60
		params[:status][:break_time] = params[:status][:hour].to_i * 60 * 60 + params[:status][:mins].to_i * 60
		
		@status = current_user.statuses.new(status_params)				
    @status.save  		
  	redirect_to status_path('show')
  		#render 'show'					
	end

	def show
	end

	private
	def status_params
		params.require(:status).permit(:subject, :date, :in_time, :out_time, :project_name, :client_name, :co_ordinator, :work_hour, :break_time, :meeting_description, :total_task, :task_description, :status_msg, :resion)
	end
end

app/controllers/users_invitations_controller.rb
class UsersInvitationsController < Devise::InvitationsController


	def edit
	  render :edit, :layout => false
	end

  def new
    @user = User.new
  end

  def create
	 @user = User.new(user_params)
	 @user.save
  end
  
	def update
    User.create(params[:user].require(:user).permit(:email,:first_name,:last_name))
		self.resource = resource_class.accept_invitation!(resource_params)
		 
		if resource.errors.empty?
			flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
			set_flash_message :notice, flash_message
			sign_in(resource_name, resource)
			 
			redirect_to edit_user_registration_path
	  else
			respond_with_navigational(resource){ render :edit, :layout => false }
    end
  end

	private
  def user_params    
	  params.require(:user).permit(:email, :first_name, :last_name)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper	
	def get_checkout(attendence1)			
		Time.at((attendence1.workhour).to_i).gmtime.strftime('%R:%S')				
	end	
	def get_intime(intimem)			
		intime.in_time.strftime("%r")					
	end
	def get_outtime(outtime)		
		outtime.out_time.strftime("%r")				
	end		
	def get_totalworkhour(tworkhour)			
		Time.at((tworkhour.workhour).to_i).gmtime.strftime('%R:%S')			
	end	
end

app/helpers/projects_helper.rb
module ProjectsHelper
	
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper	
	def get_intime(intime)
		return intime.in_time.strftime("%r")				
	end

	def get_outtime(outtime)		
  	return outtime.out_time.strftime("%r")		
	end

	def get_tworkhour(tworkhour)
  	return Time.at(tworkhour.work_hour).gmtime.strftime('%R:%S')				
	end	
	
	def get_breaktime(brktime)	
		return Time.at(brktime.break_time).gmtime.strftime('%R:%S')				
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/attendence.html.erb
<div style="width:70%;float:left;">
	<table id="aat1">
		<tr bgcolor="#D3D3D3">
			<th id="aat2">ID</th>
			<th id="aat2">IN_Date</th>
			<th id="aat2">IN_Time</th>
			<th id="aat2">OUT_Date</th>
			<th id="aat2">OUT_Time</th>
			<th id="aat2">WORK_Hour</th>
			<th id="aat2">IP_IN</th>
			<th id="aat2">IP_OUT</th>
			<th id="aat2">Status</th>
		</tr>
		<% @attendence.each do |attendence| %>

			<tr>
				<td id="aat3"><%= attendence.id %></td>
				<td id="aat3"><%= attendence.in_date %></td>
				<td id="aat3"><%= get_intime(attendence) %></td>
				<td id="aat3"><%= attendence.out_date %></td>
				<td id="aat3"><%= get_outtime(attendence) %></td>
				<td id="aat3"><%= get_checkout(attendence) %></td>
				<td id="aat3"><%= attendence.ip_in %></td>
				<td id="aat3"><%= attendence.ip_out %></td>
				<td id="aat3"><%= attendence.status %></td>
			</tr>
		<% end %>
	</table>
	<p>
	  <h3>Download:
		<%= link_to "Excel_Format ", attendence_admin_user_path(format: "xls") %>
	</p>
</div>
<div style="width:29%">
	<table border="1">
		<tr>
			<th>Email</th>
			<th>IN_Date</th>
			<th>Total_WORK_Hour</th>
		</tr>
		<% @attendences.each do |attendence| %>
			<tr>
				<td><%= User.find(attendence.user_id).email %></td>
				<td><%= attendence.in_date %></td>	
				<td><%= get_totalworkhour(attendence) %></td>						
			</tr>
		<% end %>
	</table>
</div>
<br/>
<p>
  <h3>Download:
		<%= link_to "Excel_Format ", attendences_admin_user_path(format: "xls") %>
	</h3>
</p>
		

		

app/views/admin/users/attendence.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">IN_Date</Data></Cell>
        <Cell><Data ss:Type="String">IN_Time</Data></Cell>
        <Cell><Data ss:Type="String">OUT_Date</Data></Cell>
        <Cell><Data ss:Type="String">OUT_Time</Data></Cell>
        <Cell><Data ss:Type="String">WORK_Hour</Data></Cell>
        <Cell><Data ss:Type="String">IP_IN</Data></Cell>
        <Cell><Data ss:Type="String">IP_OUT</Data></Cell>        
      </Row>
    <% @attendence.each do |attendence| %>      
      <Row>
        <Cell><Data ss:Type="Number"><%= attendence.id %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= attendence.in_date %></Data></Cell>
        <Cell><Data ss:Type="Time"><%= attendence.in_time %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= attendence.out_date %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= attendence.out_time %></Data></Cell>
        <Cell><Data ss:Type="String"><%= attendence.workhour %></Data></Cell>
        <Cell><Data ss:Type="String"><%= attendence.ip_in %></Data></Cell>
        <Cell><Data ss:Type="String"><%= attendence.ip_out %></Data></Cell>    
      </Row>
    <% end %>
    </Table>
  </Worksheet>  
</Workbook>

app/views/admin/users/attendences.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">IN_Date</Data></Cell>
        <Cell><Data ss:Type="String">Total_Work_Hour</Data></Cell>
      </Row>
    <% @attendences.each do |attendence| %>
      <Row>
        <Cell><Data ss:Type="String"><%= User.find(attendence.user_id).email %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= attendence.in_date %></Data></Cell>        
        <Cell><Data ss:Type="String"><%= attendence.workhour %></Data></Cell>
        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/users/new_invitation.html.erb
<h2>Send invitation</h2>
<%= form_for @user, :url => send_invitation_admin_users_path do |f| %>       
	<table>		
		<tr>		
			<td><%= f.label :first_name %></td>
			<td><%= f.text_field :first_name %></td>
		</tr>
		<tr>
			<td><%= f.label :last_name %></td>
			<td><%= f.text_field :last_name %></td>
		</tr>
		<tr>
			<td><%= f.label :email %></td>
			<td><%= f.text_field :email, :required => true %></td>
		</tr>
		
		</table>		
		   <%= f.submit "Send an Invitation" %>
<% end %>		 
	

app/views/admin/users/project.html.erb
<table id="ast1">
	<tr bgcolor="#D3D3D3">
		<th id="ast2">ID</th>
		<th id="ast2">Project_Name</th>
		<th id="ast2">Client_Name</th>
		<th id="ast2">Co_Ordinator</th>
		<th id="ast2">About_Project_Work</th>
		<th id="ast2">Started_Date</th>
	</tr>
	<% @projects.each do |project| %>

		<tr>
			<td id="ast3"><%= project.id %></td>
			<td id="ast3"><%= project.proj_name %></td>
			<td id="ast3"><%= project.client_name %></td>
			<td id="ast3"><%= project.co_ordinator %></td>
			<td id="ast3"><%= project.about_project_work %></td>
			<td id="ast3"><%= project.started_date %></td>
			</tr>
	<% end %>
</table>

app/views/admin/users/status.html.erb
<table id="ast1">
	<tr bgcolor="#D3D3D3">
		<th id="ast2">Subject</th>
		<th id="ast2">Date</th>
		<th id="ast2">IN_Time</th>
		<th id="ast2">OUT_Time</th>
		<th id="ast2">Project_Name</th>
		<th id="ast2">Client_Name</th>
		<th id="ast2">Co_Ordinator</th>
		<th id="ast2">Work_Hour</th>
		<th id="ast2">Break_Time</th>
		<th id="ast2">Meeting_Description</th>
		<th id="ast2">Task_Description</th>
		<th id="ast2">Reason</th>
	</tr>
	<% @status.each do |status| %>
		<tr>
			<td id="ast3"><%= status.subject %></td>
			<td id="ast3"><%= status.date %></td>
			<td id="ast3"><%= get_intime(status) %></td>
			<td id="ast3"><%= get_outtime(status) %></td>
			<td id="ast3"><%= status.project_name %></td>
			<td id="ast3"><%= status.client_name %></td>
			<td id="ast3"><%= status.co_ordinator %></td>
			<td id="ast3"><%= get_tworkhour(status) %></td>
			<td id="ast3"><%= get_breaktime(status) %></td>
			<td id="ast3"><%= status.meeting_description %></td>
			<td id="ast3"><%= status.task_description %></td>
			<td id="ast3"><%= status.resion %></td>
		</tr>
	<% end %>
</table>

app/views/attendences/checkin.html.erb
<%= form_for @attendence, :url => attendences_path do |f| %>
<table>
	 <tr>
	   <th>Indate</th>
	   <th>intime</th>
	 </tr>
	  <td><%= f.text_field :in_date %></td>
	  <td><%= f.text_field :in_time %></td>
	 </tr>
</table>
 <%= f.submit "Update checkin" %>
 <% end %>

app/views/attendences/checkout.html.erb
<%= form_for @attendence, :url => attendences_path do |f| %>
	<table>
		 <tr>
		   <th>OutDate</th>
		   <th>OutTime</th>
		   <th>WorkHour</th>
		 </tr>
		  <td><%= f.text_field :out_date %></td>
		  <td><%= f.text_field :out_time %></td>
		  <td><%= f.text_field :workhour %></td>
		 </tr>
	</table>
 <%= f.submit "Update checkin" %>
 <% end %>

app/views/attendences/index.html.erb
<% if current_user.attendences.blank? %>
	<%= link_to 'CheckIn', checkin_attendences_path %>
<% else %>
	<% if Attendence.where(:user_id => current_user.id).last.out_date.blank? %>
		<%= link_to 'CheckOut', checkout_attendences_path %>
	<% else %>
		<%= link_to 'CheckIn', checkin_attendences_path %>
	<% end %>
<% end %>

app/views/attendences/status.html.erb
<%= form_for @attendence, :url => attendences_path do |f| %>
<table>
	 <tr>
	   <th>Indate</th>
	   <th>intime</th>
	 </tr> 
	  <td><%= f.text_field :indate %></td>
	 </tr>
	 <tr>
	   <td><%= f.text_field :intime %></td>
	 </tr>
</table>
 <%= f.submit "Update checkin" %>
 <% end %>
       

app/views/layouts/_header.html.erb
<div id="head">
	<span>GrepRuby</span>
	<% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong>.
		<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		<%= link_to 'Status', new_status_path, :class => 'navbar-link' %> |
		<%= link_to 'Project', new_project_path, :class => 'navbar-link' %> |
		<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
		<%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
</div>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Devis</title>
      <link rel="stylesheet" type="text/css" href="style.css">

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>
   <body>
      <div class="wrapper">        
        <%= render :partial => "layouts/header"%>
        <div id="content">
          <%= yield %>
        </div>
        <div id="footer">
          <%= render :partial => "layouts/footer" %>     
        </div>
      </div>
    </body>
    
</html>

app/views/projects/new.html.erb
<%= form_for @project, :url=>projects_path do |f| %>
<div id="wrp1">
	<table>
		<tr>
			<td id="wrp2">Project_Name</td>
			<td id="wrp2"><%= f.text_field :proj_name,:required=>"required" %></td>
		</tr>		
		<tr>
			<td>Client_Name</td>
			<td><%= f.text_field :client_name,:required=>"required"%></td>
		</tr>
		<tr>
			<td id="wrp3">Co_Ordinator</td>
			<td id="wr2"><%= f.text_field :co_ordinator %></td>
		</tr>
		<tr>
			<td id="wrp6">About_Project_Work</td>
			<td><%= f.text_area :about_project_work,:required=>"required" %></td>
		</tr>
		<tr>
			<td id="wrp4">Started_Date</td>
			<td><%= f.text_field :started_date, 'data-behaviour' => 'datepicker', :placeholder=> 'dd:mm:yyyy' %></td>
		</tr>
		<tr>
			<td id="wrp5"><%= f.submit "Submit Project" %></td>
		</tr>
		
	</table>
	</div>
<% end %>
























		

app/views/statuses/new.html.erb
<%= form_for @status, :html => { :onsubmit => 'return validate();' }, :url=>statuses_path do |f| %>
<div id="wr">
	<table>
		<tr>
			<td id="wr1">Subject<span class="red">  *</span></p></td>
			<td id="wra1"><%= f.text_field :subject %></td>
			<td><p id="reqsub"></td>
		</tr>
		<tr>
			<td>Project_Name<span class="red">  *</span></td>
			<td><%= f.text_field :project_name, :class=>'txt1' %></td>
			<td><p id="reqname"></td>
		</tr>
		<tr>
			<td>Client_Name<span class="red">  *</span></td>
			<td><%= f.text_field :client_name %></td>
			<td><p id="reqcname"></td>
		</tr>
		<tr>
			<td id="wr2">Co_Ordinator<span class="red">  *</span></td>
			<td id="wr2"><%= f.text_field :co_ordinator %></td>	
			<td><p id="reqconame"></td>	
		</tr>
		<tr>
			<td>Date</td>
			<td><%= f.text_field :date, 'data-behaviour' => 'datepicker', :placeholder=> 'dd:mm:yyyy' %></td>
		</tr>
		<tr>
			<td>In_Time</td>
			<td><%= f.time_select :in_time, {ampm: true} %></td>
		</tr>
		<tr>
			<td>Out_Time</td>
			<td><%= f.time_select :out_time, {ampm: true} %></td>
		</tr>		
		<tr>
			<td>Working_Hour</td>
			<td><%#= f.time_select :work_hour %>	
			 <%= select(:status, :hour1, [['Select in Hours', '00'],['1', '1'], ['2', '2'], ['3', '3'],['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10'], ['11', '11'], ['12', '12']]) %>
 				<%= select(:status, :mins1, [['Select in Minutes', '00'],['00', '00'],['10', '10'], ['20', '20'], ['30', '30'],['40', '40'], ['50', '50']]) %>
			</td>
		</tr>
		<tr>
			<td id="wr3">Break_Time</td>
			<td id="wr3"><%#= f.time_select :break_time %>
				<%= select(:status, :hour, [['Select in Hours', '00'],['1', '1'], ['2', '2'], ['3', '3'],['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10']]) %>
 				<%= select(:status, :mins, [['Select in Minutes', '00'],['00', '00'],['10', '10'], ['20', '20'], ['30', '30'],['40', '40'], ['50', '50']]) %>
			</td>	
		</tr>
		<tr>
			<td>Meeting_Description</td>
			<td><%= f.text_area :meeting_description %></td>		
		</tr>
		<tr>
			<td>Task_Description</td>
			<td><%= f.text_area :task_description %></td>		
		</tr>
		<tr>
			<td>Reason</td>
			<td><%= f.text_area :resion %></td>
		</tr>
		<tr>
			<td id="btn1"><%= f.submit "Update Status" %></td>
		</tr>
	</table>
	</div>
<% end %>


 

app/views/statuses/newstatus.html.erb
<%= form_for @status, :url=>statuses_path do |f| %>
<div id="wr">
	<table>
		<tr>
			<td id="wr1">Subject</td>
			<td id="wrp"><%= f.text_field :subject %></td>
		</tr>
		<tr>
			<td>Project_Name</td>
			<td><%= f.text_field :project_name %></td>
		</tr>
		<tr>
			<td>Client_Name</td>
			<td><%= f.text_field :client_name %></td>
		</tr>
		<tr>
			<td id="wr2">Co_Ordinator</td>
			<td id="wr2"><%= f.text_field :co_ordinator %></td>		
		</tr>
		<tr>
			<td>Date</td>
			<td><%= f.text_field :date %></td>
		</tr>
		<tr>
			<td>In_Time</td>
			<td><%= f.text_field :in_time %></td>
		</tr>
		<tr>
			<td>Out_Time</td>
			<td><%= f.text_field :out_time %></td>
		</tr>		
		
		<tr>
			<td>Working_Hour</td>
			<td><%= f.text_field :work_hour %></td>		
		</tr>
		<tr>
			<td id="wr3">Break_Time</td>
			<td id="wr3"><%= f.text_field :break_time %></td>		
		</tr>
		<tr>
			<td>Meeting_Description</td>
			<td><%= f.text_area :meeting_description %></td>		
		</tr>
		<tr>
			<td>Task_Description</td>
			<td><%= f.text_area :task_description %></td>		
		</tr>
		<tr>
			<td>Reason</td>
			<td><%= f.text_area :resion %></td>
		</tr>
		<tr>
			<td><%= f.submit "Update Status" %></td>
		</tr>
	</table>
	</div>
<% end %>

app/views/statuses/show.html.erb
<h1>Successfully updated status!!</h1>
<%= link_to 'Home', checkout_attendences_path, :class => 'navbar-linkss' %>

app/views/statuses/statusshow.html.erb
<h1>Successfully updated status!!</h1>
<%= link_to 'Home', checkout_attendences_path, :class => 'navbar-linkss' %>

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/welcome/index.html.erb
<%= link_to 'Click Forrr Home', controller: 'attendences' %>